version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  auth:
    cmds:
      - cd cmd/auth && go run main.go

  migrate:
    desc: migrate db
    cmds:
      - cd cmd/migrate && go run main.go {{.CLI_ARGS}}
