version: '3'

dotenv: ['.env.local']

tasks:
  gen-sql:
    cmds:
      - sqlc generate

  migrate:
    desc: migrate db
    cmds:
      - cd cmd/migrate && go run main.go {{.CLI_ARGS}}

  auth:
    cmds:
      - cd cmd/auth && go run main.go

  location_ingestion:
    cmds:
      - cd cmd/location_ingestion && go run main.go

  location_processing:
    cmds:
      - cd cmd/location_processing && go run main.go

  location_query:
    cmds:
      - cd cmd/location_query && go run main.go
