version: '3'

dotenv: ['.env.local']

tasks:
  auth:
    cmds:
      - cd cmd/auth && go run main.go

  location_ingestion:
    cmds:
      - cd cmd/location_ingestion && go run main.go

  migrate:
    desc: migrate db
    cmds:
      - cd cmd/migrate && go run main.go {{.CLI_ARGS}}
