// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package locationRepo

import (
	"time"

	"github.com/cridenour/go-postgis"
)

type Location struct {
	ID        int64         `db:"id" json:"id"`
	UserID    int64         `db:"user_id" json:"user_id"`
	Geometry  postgis.Point `db:"geometry" json:"geometry"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
}
